PLUGIN_NAME=		acme-client
PLUGIN_VERSION=		3.18
PLUGIN_COMMENT=		ACME Client
PLUGIN_MAINTAINER=	pfwsense@moov.de
PLUGIN_DEPENDS=		acme.sh py${PLUGIN_PYTHON}-dns-lexicon

.include "../../Mk/plugins.mk"
