PLUGIN_NAME=		lcdproc-sdeclcd
PLUGIN_VERSION=		1.1
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		LCDProc for SDEC LCD devices
PLUGIN_DEPENDS=		lcdproc
PLUGIN_MAINTAINER=	ad@pfwsense.org

.include "../../Mk/plugins.mk"
