PLUGIN_NAME=		cache
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Webserver cache
PLUGIN_DEPENDS=		php${PLUGIN_PHP}-opcache
PLUGIN_MAINTAINER=	ad@pfwsense.org

.include "../../Mk/plugins.mk"
