PLUGIN_NAME=		qemu-guest-agent
PLUGIN_VERSION=		1.2
PLUGIN_COMMENT=		QEMU Guest Agent for PFWsense
PLUGIN_DEPENDS=		qemu-guest-agent
PLUGIN_MAINTAINER=	pfwsense@moov.de

.include "../../Mk/plugins.mk"
