# DO NOT EDIT THIS FILE -- PFWsense auto-generated file
{% if helpers.exists('PFWsense.crowdsec.general.firewall_bouncer_enabled') and PFWsense.crowdsec.general.firewall_bouncer_enabled|default("1") == "1" %}
crowdsec_firewall_enable="YES"
{% else %}
crowdsec_firewall_enable="NO"
{% endif %}
{% if helpers.exists('PFWsense.crowdsec.general.crowdsec_firewall_verbose') and PFWsense.crowdsec.general.crowdsec_firewall_verbose|default("0") == "1" %}
crowdsec_firewall_flags="-v"
{% else %}
crowdsec_firewall_flags=""
{% endif %}
