# DO NOT EDIT THIS FILE -- PFWsense auto-generated file
{% if helpers.exists('PFWsense.relayd.general.enabled') and PFWsense.relayd.general.enabled|default("0") == "1" %}
osrelayd_enable="YES"
{% else %}
osrelayd_enable="NO"
{% endif %}
